mode:
    production

production:
    datasources:
        mysql:
          disable: true
        mongodb:
           disable: true
        redis:
           disable: true

test:
    datasources:
        mysql:
           disable: true
        mongodb:
           disable: true

application:
    controller: streaming.rest
    service:
    util:
    test:
    static:
           enable: true
    template:
        engine:
           enable: true

serviceframework:
    template:
        loader:
             classpath:
                  enable: true
    static:
        loader:
             classpath:
                  enable: true
                  dir: "streamingpro/assets"
###############http config##################
http:
    disable: false
    host: 0.0.0.0
    class:
        port: streaming.common.SpecificPortGenerator
thrift:
    disable: true
dubbo:
    disable: true



