mode:
    production

production:
    datasources:
        mysql:
            disable: true
        mongodb:
           disable: true
        redis:
           disable: true

test:
    datasources:
        mysql:
           disable: true
        mongodb:
           disable: true

application:
    controllerNames: streaming.rest.RestController
    service:
    util:
    test:
    static:
           enable: true
    template:
        engine:
           enable: true

serviceframework:
    template:
        loader:
             classpath:
                  enable: true
    static:
        loader:
             classpath:
                  enable: true
                  dir: "streamingpro/assets"
###############http config##################
http:
    disable: false
    class:
        port: streaming.common.SpecificPortGenerator
thrift:
    disable: true
dubbo:
    disable: true



